### ISSUE TITLE
Slight issues in Terminal, Hidden, and Acceptable Losses

### ISSUE THREAD

**Issue by Knight450** [fedddddd/h2-specops-mod#21]
In Terminal, at the side of the escalators where the Riot Shield Soldiers come out of, one of them does not move from his position even after being provoked. At the start, the blue mat will become invisible when turning the camera. In Hidden, the game's materials may break and result in blue/pixelated textures at a distance (fixes upclose but reverts back at a distance). The AK that can be picked up at the start of Acceptable Losses has an animation issue where if you sprint with it, its help as if there is an under-barrel attachment when it doesn't contain one.

Riot Soldier that stood there even after two checkpoints:
https://i.imgur.com/l82hQto.jpg

Disappearing model:
https://i.imgur.com/eFrUNGh.jpg
https://i.imgur.com/MW6iQnD.jpg

Hidden material bug (possibly happens if the mission is restarted after failing):
https://i.imgur.com/Xq1iU7w.jpg

Edit:
It seems the AI can go out of bounds on Evasion (I thought it was strange to see them running near the start when they seemed to not have spotted me but I wasn't given a warning). I was sneaking right next to the fence and I saw a squad with a dog run on the opposite of the fence and jump across and then spot me.

**Comment by fedddddd** [comment]
1 dupe of  #14 
2 wont fix
3 issue with h2-zonetool
4 base game issue, every AK in the game does that
5 expected behaviour
