### ISSUE TITLE
Where can I find a asslist file

### ISSUE THREAD

**Issue by Animuses** [fedddddd/h2-specops-mod#24]
I'm doing simplified chinese localization for this mod, it works pretty good in menu and loading screen. But it looks like missing fonts or a list of fonts in game. I will appreciate if somebody tells me a way to find this missing asset.
![(RUHTHLRZPRVFHU}9)@7DR8](https://user-images.githubusercontent.com/92357353/217120252-75e5f423-596b-4609-9d49-7dd100cec7bd.png)
![9G$WZ16LCK}72~L_Y`)(7A4](https://user-images.githubusercontent.com/92357353/217120259-a10ff02a-cb9c-4155-9b99-56634be7e3a4.png)

**Comment by fedddddd** [comment]
That file has no purpose so that error can be ignored
